controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joints_controller:
      type: forward_command_controller/ForwardCommandController

arm_joints_controller:
  ros__parameters:
    joints: ["joint1", "joint2"]
    interface_name: "position"
